import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="min-h-[calc(100dvh-4rem)] md:min-h[calc(100dvh-5rem)]">
          {children}
        </main>
      </body>
    </html>
  );
}
